### ISSUE TITLE
topo-sort and topo-comparator not deterministic

### ISSUE THREAD

**Issue by weavejester** [stuartsierra/dependency#6]
I've noticed that `topo-sort` and `topo-comparator` are not deterministic, and because `topo-comparator` depends on `topo-sort`, there doesn't appear to be any way to force a deterministic ordering.

I've probably missed something obvious, but is there a reason this wouldn't work:

```clojure
(defn topo-comparator [graph]
  (fn [a b]
    (cond
      (depends? graph a b) 1
      (depends? graph b a) -1
      :else 0)))
```

Or is the reason that wasn't chosen because of performance?

**Comment by weavejester** [comment]
I see the problem with writing a `topo-comparator` using `depends?` now. Because the dependency graph isn't linear, that function will fail under some orderings.

**Comment by stuartsierra** [comment]
Hi, thanks for looking into this! I see the issue that you are describing: I think the key is that while `topo-sort` is *deterministic* (same input values will produce the same output), it is not a *stable* sort. Sometimes it will reorder input elements that do not have any dependency relationship.

I believe this is actually necessary to satisfy the contract of [java.util.Comparator](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html) which requires a *total ordering* on elements. There are [better algorithms](https://en.wikipedia.org/wiki/Topological_sorting) for a true 
partial-order topological sort, maybe some of them are also a stable sort.

However, changing the API for a library this old would almost certainly break something downstream, especially since 'dependency' was primarily used to support dev utilities such as tools.namespace and Component. It was never intended to be a general-purpose graph library, which is better-served by [Loom](https://github.com/aysylu/loom) or other libraries.

**Comment by weavejester** [comment]
Thanks for the reply. For now I've forked the project, but I'll take a look at Loom and see if that will work better. If not, then my fork should work fine.
